### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by ace-roger** [ishan3199/central-system#2]
Hi Ishan,

I want to use ocpp protocol for the charging cycle but mainly smart charging - 

1. Start charging session - statusNotification, Authorization, and startTransaction
2. Charging Profile - setChargingProfile, recceive meter values
3. Stop charging session - stopTransaction

Can you guide me on how should I proceed?

**Comment by ishan3199** [comment]
Hey ace! How are you today?

Yes sure, I can guide you there! Can I know what are your exact requirements and also what framework and programming software are you planning to use? I assume that you are only dealing with developing the server for now, right?  

Perhaps, can you share me your email so we can take this issue there?

Best,
Ishan
